In [4]:
import torch.nn as nn
import torch.nn.functional as F
import torch 
print(torch.__version__) 
import torch.nn.utils
import torch.nn.utils.prune as prune

1.4.0


In [2]:
class testModel(nn.Module):
    def __init__(self):
        super(testModel,self).__init__()
       
        
        self.mike = nn.Conv1d(
            in_channels = 3,
            out_channels = 6,
            kernel_size = 3,
            stride = 3,
            padding = 0,
            groups = 3)
        
    def forward(self, x):
        leaky = nn.LeakyReLU(0.01)
        x = leaky(self.mike(x))
        
        params = list(self.parameters())
        print(len(params))
        print(params[0].size())  # conv1's .weight
        return x

In [3]:
input = torch.randn(2,3,5)
print("input.size() = ", input.size()) ## size() is a function
print("input.shape = ",input.shape)  ## shape is an attribute
print("input = ",input)
m = testModel()
output = m(input)

print("  ")
print("output.size() = ", output.size())
print("output = ",output)

print("  ")



input.size() =  torch.Size([2, 3, 5])
input.shape =  torch.Size([2, 3, 5])
input =  tensor([[[-0.2314, -0.1660,  2.6358,  0.3446,  0.0806],
         [-0.7033, -0.4945, -0.0315, -2.3155,  2.0548],
         [ 0.3508, -0.2263, -0.1728, -0.2293, -0.5760]],

        [[ 0.2031,  0.9739, -0.2447,  0.0553, -0.9320],
         [-1.2844,  0.8001,  0.6534, -1.5039,  0.4885],
         [-1.3670, -0.2455, -0.1996, -1.1903,  0.8448]]])
2
torch.Size([6, 1, 3])
  
output.size() =  torch.Size([2, 6, 1])
output =  tensor([[[ 1.4315],
         [ 0.5674],
         [ 0.4660],
         [ 0.2794],
         [ 0.2081],
         [ 0.3380]],

        [[ 0.5222],
         [-0.0019],
         [ 0.4765],
         [ 0.4603],
         [-0.0047],
         [ 1.3449]]], grad_fn=<LeakyReluBackward0>)
  


In [10]:
module = m.mike
print(list(module.named_parameters()))

print(" between commands")
print(list(module.named_buffers()))

[('bias', Parameter containing:
tensor([ 0.2970, -0.3209,  0.3810,  0.3793,  0.1972,  0.3879],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[-0.4698,  0.4339,  0.4165]],

        [[ 0.0033,  0.2248,  0.3515]],

        [[-0.2157,  0.1656, -0.4808]],

        [[-0.0234,  0.2497, -0.2277]],

        [[ 0.3878,  0.1548,  0.5214]],

        [[-0.5767, -0.4616, -0.2776]]], requires_grad=True))]
 between commands
[('weight_mask', tensor([[[1., 1., 1.]],

        [[0., 0., 0.]],

        [[1., 0., 0.]],

        [[0., 1., 0.]],

        [[1., 1., 1.]],

        [[1., 0., 0.]]]))]


In [8]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv1d(3, 6, kernel_size=(3,), stride=(3,), groups=3)

In [7]:
print(list(module.named_parameters()))

[('bias', Parameter containing:
tensor([ 0.2970, -0.3209,  0.3810,  0.3793,  0.1972,  0.3879],
       requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[-0.4698,  0.4339,  0.4165]],

        [[ 0.0033,  0.2248,  0.3515]],

        [[-0.2157,  0.1656, -0.4808]],

        [[-0.0234,  0.2497, -0.2277]],

        [[ 0.3878,  0.1548,  0.5214]],

        [[-0.5767, -0.4616, -0.2776]]], requires_grad=True))]


In [9]:
print(module.weight)

tensor([[[-0.4698,  0.4339,  0.4165]],

        [[ 0.0000,  0.0000,  0.0000]],

        [[-0.2157,  0.0000, -0.0000]],

        [[-0.0000,  0.2497, -0.0000]],

        [[ 0.3878,  0.1548,  0.5214]],

        [[-0.5767, -0.0000, -0.0000]]], grad_fn=<MulBackward0>)
